mpi:
  - mpich
  - openmpi
scalar:
  - real
  - complex
pin_run_as_build:
  petsc:
    max_pin: x.x
  suitesparse:
    max_pin: x.x  # [linux]
    # extra pinning due to conda-forge/suitesparse-feedstock#22
    max_pin: x.x.x  # [osx]
