{% set version = "3.9.2" %}
{% set sha256 = '247585b3f8c10bf50b9464cb8ef7b5f22bead6f96524384897a37ec4146eb03e' %}

package:
  name: slepc
  version: {{version}}

source:
  fn:  slepc-{{version}}.tar.gz
  url: http://slepc.upv.es/download/distrib/slepc-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  skip: true  # [win]
  # ensure compilers are in host env
  # so we find libgcc_ext.10.5
  # I think it's a mistake that petsc looks for this lib
  merge_build_host: true  # [osx]
  number: 0
  # do not remove feature until blas mpkg stops using track_features
  features:
    - blas_openblas
  run_exports:
    - {{ pin_subpackage('slepc', min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python 2.7.*
    - {{ mpi }}
    - openblas
    - petsc
    - suitesparse
  run:
    - {{ mpi }}
    - openblas
    - petsc
    - suitesparse

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - pkg-config
  files:
    - tests/test10.c
    - tests/test14f.F
    - tests/makefile
  commands:
    - conda inspect objects  slepc  # [osx]
    - conda inspect linkages slepc  # [not win]
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
