{% set version = "3.9.0" %}
{% set sha256 = '1f3930db56b4065aaf214ea758ddff1a70bf19d45544cbdfd19d2787db4bfe0b' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: slepc
  version: {{version}}

source:
  fn:  slepc-{{version}}.tar.gz
  url: http://slepc.upv.es/download/distrib/slepc-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  skip: true  # [win]
  number: 0
  binary_relocation: true
  detect_binary_files_with_prefix: true
  features:
    - blas_{{blas}}

requirements:
  build:
    - gcc  # [not win]
    - toolchain
    - python 2.7.*
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas 0.2.20
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - petsc {{version[:3]}}*
  run:
    - libgcc  # [linux]
    - libgfortran  # [osx]
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas 0.2.20
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - petsc {{version[:3]}}*

test:
  requires:
    - gcc  # [not win]
    - pkg-config
  files:
    - tests/test10.c
    - tests/test14f.F
    - tests/makefile
  commands:
    - conda inspect objects  slepc  # [osx]
    - conda inspect linkages slepc  # [not win]
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
