{% set build = 0 %}
{% set version = '3.8.2' %}
{% set sha256 = '1e7d20d20eb26da307d36017461fe4a55f40e947e232739179dbe6412e22ed13' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set openblas_version = '0.2.20|0.2.20.*' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: slepc
  version: {{version}}

source:
  fn:  slepc-{{version}}.tar.gz
  url: http://slepc.upv.es/download/distrib/slepc-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  skip: true  # [win]
  number: {{build}}
  binary_relocation: true
  detect_binary_files_with_prefix: true
  features:
    - blas_{{blas}}

requirements:
  build:
    - gcc  # [not win]
    - toolchain
    - python 2.7.*
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas {{openblas_version}}
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - petsc {{version[:3]}}*
  run:
    - libgcc  # [linux]
    - libgfortran  # [osx]
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas {{openblas_version}}
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - petsc {{version[:3]}}*

test:
  requires:
    - gcc  # [not win]
    - pkg-config
  source_files:
    - src/eps/examples/tests
  commands:
    - conda inspect linkages petsc  # [not win]
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
