{% set version = "3.13.4" %}
{% set sha256 = "a586ce572a928ed87f04961850992a9b8e741677397cbaa3fb028323eddf4598" %}

{% set version_xy = version.rsplit(".", 1)[0] %}
{% set mpi = mpi or 'mpich' %}

package:
  name: slepc
  version: {{ version }}

source:
  url: http://slepc.upv.es/download/distrib/slepc-{{ version }}.tar.gz
  sha256: ddc9d58e1a4413218f4e67ea3b255b330bd389d67f394403a27caedf45afa496

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage('slepc', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - python
  host:
    - libblas
    - libcblas
    - liblapack
    - {{ mpi }}
    - petsc {{ version_xy }}.*
    - suitesparse
  run:
    - {{ mpi }}
    - petsc
    - suitesparse

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  files:
    - tests/test10.c
    - tests/test14f.F
    - tests/makefile
  commands:
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD-2-Clause
  license_file: LICENSE.md
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
