{% set version = "3.8.3" %}
{% set sha256 = '60a10ba01151b904f68b52f6d5da5830acf5f82ad7d9778711e62ffcf82ec2ca' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: slepc
  version: {{version}}

source:
  fn:  slepc-{{version}}.tar.gz
  url: http://slepc.upv.es/download/distrib/slepc-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  skip: true  # [win]
  number: 0
  binary_relocation: true
  detect_binary_files_with_prefix: true
  features:
    - blas_{{blas}}

requirements:
  build:
    - gcc  # [not win]
    - toolchain
    - python 2.7.*
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas 0.2.20|0.2.20.*
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - petsc {{version[:3]}}*
  run:
    - libgcc  # [linux]
    - libgfortran  # [osx]
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas 0.2.20|0.2.20.*
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - petsc {{version[:3]}}*

test:
  requires:
    - gcc  # [not win]
    - pkg-config
  source_files:
    - src/eps/examples/tests
  commands:
    - conda inspect linkages petsc  # [not win]
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
