{% set build = 1 %}
{% set version = '3.8.0' %}
{% set sha256 = 'c58ccc4e852d1da01112466c48efa41f0839649f3a265925788237d76cd3d963' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: slepc
  version: {{version}}

source:
  fn:  slepc-{{version}}.tar.gz
  url: http://slepc.upv.es/download/distrib/slepc-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  skip: true  # [win]
  number: {{build}}
  binary_relocation: true
  detect_binary_files_with_prefix: true
  features:
    - blas_{{blas}}

requirements:
  build:
    - toolchain
    - python 2.*
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas 0.2.20|0.2.20.*
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - petsc {{version[:3]}}*
  run:
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas 0.2.20|0.2.20.*
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - petsc {{version[:3]}}*

test:
  source_files:
    - src/eps/examples/tests
  requires:
    - pkg-config
  commands:
    - conda inspect linkages petsc  # [not win]
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
