{% set version = "3.17.2" %}
{% set sha256 = "f784cca83a14156631d6e0f5726ca0778e259e1fe40c927607d5fb12d958d705" %}
{% set build = 0 %}

{% set version_xy = version.rsplit(".", 1)[0] %}
{% set mpi = mpi or 'mpich' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: slepc
  version: {{ version }}

source:
  url: http://slepc.upv.es/download/distrib/slepc-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: {{ build }}
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('slepc', max_pin='x.x') }} {{ scalar }}_*
  track_features:
    - slepc_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - python
    - gnuconfig
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - libblas
    - libcblas
    - liblapack
    - {{ mpi }}
    - petsc {{ version_xy }}.* {{ scalar }}_*
    - suitesparse
  run:
    - {{ mpi }}
    - petsc
    - suitesparse

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  files:
    - tests/test10.c
    - tests/test14f.F
    - tests/makefile
  commands:
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD-2-Clause
  license_file: LICENSE.md
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
